final List<String> customNotificationMessages = [
  "🚀 Ready to launch your learning today?",
  "🌌 Explore a new concept in your space journey!",
  "🪐 Time to orbit your goals!",
  "👩‍🚀 Gear up for a new discovery session!",
  "🌠 Study stars are aligning just for you!",
  "🌙 Fuel up your brain – it's time for liftoff!",
  "🛰️ Transmitting today’s knowledge capsule…",
  "💫 Gravity won’t hold you back—time to study!",
  "🌍 Ground control to curious mind: begin mission.",
  "🌟 A stellar session awaits. Ready to shine?",
  "☄️ Hit warp speed on your learning goals!",
  "🚀 Boost your brainpower beyond the stratosphere!",
  "🌕 Study like it's a full moon night—bright and focused!",
  "🛸 Dive into the unknown—study something new today!",
  "👨‍🚀 Commander, your study ship is ready for launch.",
  "📡 Receiving a signal: it’s time to focus!",
  "🌌 Chart your course through today's topics.",
  "🪄 Make a quantum leap in your knowledge today!",
];
